library(shiny)
library(shinyjs)
library(shinymaterial)
library(tidyverse)
library(httr)
library(tweetDumpR)
library(jsonlite)

ui <- material_page(
  useShinyjs(),
  title = "Tweet Generator",
  tags$br(),
  
  # Styling
  tags$style(
    "nav {
    color: #fff;
    background-color: #428bca;
    width: 100%;
    height: 56px;
    line-height: 56px;
    }"
  ),
  tags$style(
    ".btn, .btn-large {
    text-decoration: none;
    color: #fff;
    background-color: #428bca;
    text-align: center;
    letter-spacing: .5px;
    transition: .2s ease-out;
    cursor: pointer;
    }"
  ),
  tags$style(
    ".btn:focus, .btn-large:focus, .btn-floating:focus {
    background-color: #114a7b;
    }"
    ),
  tags$style(".btn:hover, .btn-large:hover {
             background-color: #114a7b;
             }"),
  tags$style(
    type = "text/css",
    ".shiny-output-error { visibility: hidden; }",
    ".shiny-output-error:before { visibility: hidden; }"
  ),
  
  # Actual app contents
  material_row(
    # Step 1/3: Get twitter data.
    material_column(
      width = 3,
      material_card(
        title = "Get Twitter data",
        textInput(
          inputId = "twitter_account",
          label = "Twitter account",
          value = "hadleywickham"
        ),
        sliderInput(
          inputId = "no_pages",
          label = "How many tweets?",
          min = 20,
          max = 800,
          value = 200,
          step = 20
        ),
        tags$h6("200 tweets takes about 10 seconds to get."),
        tags$br(),
        tags$br(),
        actionButton(inputId = "get_twitter_data", label = "Get data")
      )
    ),
    
    # Step 2/3: Parse + generate new tweets.
    material_column(
      width = 3,
      material_card(
        title = "Review tweets",
        tags$h6("A sample of the collected tweets."),
        dataTableOutput(outputId = "tweets"),
        tags$br(),
        tags$br(),
        actionButton(inputId = "make_new_tweets", label = "Make new tweets")
      )
    ),
    
    # Step 3/3: Display generated tweets.
    material_column(
      width = 6,
      material_card(
        title = "Generated tweets",
        tags$h6(
          "These tweets were automatically generated by the Markov Chain-model."
        ),
        dataTableOutput(outputId = "new_tweets")
      )
    )
  )
)

server <- function(input, output, session) {
  twitter_data = eventReactive(input$get_twitter_data, {
    print(input$twitter_account)
    material_spinner_show(session = session, output_id = "tweets")
    t = tweetDumpR::get_tweets_fast(input$twitter_account, input$no_pages /
                                      20)$text
    material_spinner_hide(session = session, output_id = "tweets")
    
    return(t)
  })
  
  new_tweets = eventReactive(input$make_new_tweets, {
    material_spinner_show(session = session, output_id = "new_tweets")
    content = httr::content(
      httr::POST(url = "https://nlg-markovify-api.herokuapp.com/generate",
                 body = jsonlite::toJSON(
                   list(
                     input_sentences = twitter_data(),
                     sentences_to_generate = 10
                   )
                 ))
    )
    material_spinner_hide(session = session, output_id = "new_tweets")
    
    return(content)
  })
  
  # Hide button to make new tweets until tweets are collected.
  observe({
    shinyjs::hide("make_new_tweets")
    if (!is.null(twitter_data()))
      shinyjs::show("make_new_tweets")
  })
  
  # Display a sample of the collected tweets.
  output$tweets = renderDataTable({
    df = twitter_data() %>%
      as.tibble() %>%
      mutate(sample = str_sub(value, 0, 60) %>% paste0(., "...")) %>%
      sample_n(5) %>%
      select(sample)
    return(df)
  },
  options = list(paging = F,
                 searching = F))
  
  # Display all generated tweets.
  output$new_tweets = renderDataTable({
    df = new_tweets() %>%
      unlist() %>%
      as.tibble() %>%
      rename(generated = value)
    return(df)
  },
  options = list(paging = F,
                 searching = F))
  
}

shinyApp(ui = ui, server = server)
